/*
 * File:        stage.h
 * Module:      orc-core/stages
 * Purpose:     Base interface for all stage types
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2025-2026 Simon Inns
 */

#pragma once

#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "../include/artifact.h"
#include "../include/node_type.h"
#include "../include/observation_context.h"
#include "../include/observation_schema.h"
#include "../include/stage_parameter.h"

namespace orc {

/**
 * @brief Report generated by a stage inspection
 *
 * Provides diagnostic information about a stage's current state,
 * useful for debugging and understanding pipeline behavior.
 */
struct StageReport {
  std::string summary;                                     // Brief overview
  std::vector<std::pair<std::string, std::string>> items;  // Label-value pairs
  std::map<std::string, std::variant<int64_t, double, std::string>>
      metrics;  // Numeric/string metrics
};

/**
 * @brief Base interface for all processing stages
 *
 * Stages transform input artifacts into output artifacts.
 * They are pure functions of their inputs and parameters.
 *
 * All stage implementations should inherit from this interface
 * and implement the required methods.
 *
 * Design Philosophy:
 * - Stages are stateless transformations
 * - All state is in artifacts (inputs/outputs)
 * - Parameters are declarative configuration
 * - Execution is deterministic and repeatable
 */
class DAGStage {
 public:
  virtual ~DAGStage() = default;

  /**
   * @brief Get stage version string
   *
   * Used for provenance tracking and compatibility checking.
   * Should follow semantic versioning (e.g., "1.2.3").
   */
  virtual std::string version() const = 0;

  /**
   * @brief Get node type information for GUI and validation
   *
   * Describes the stage's capabilities, inputs, outputs, and parameters
   * for use in the visual DAG editor and runtime validation.
   */
  virtual NodeTypeInfo get_node_type_info() const = 0;

  /**
   * @brief Execute the stage transformation
   *
   * @param inputs Input artifacts (must match required_input_count)
   * @param parameters Configuration parameters (validated against NodeTypeInfo)
   * @param observation_context Shared observation context for pipeline
   * @return Output artifacts (count matches output_count)
   *
   * This method should be pure - same inputs and parameters always
   * produce the same outputs. No side effects except through returned artifacts
   * and observations written to the context.
   */
  virtual std::vector<ArtifactPtr> execute(
      const std::vector<ArtifactPtr>& inputs,
      const std::map<std::string, ParameterValue>& parameters,
      ObservationContext& observation_context) = 0;

  /**
   * @brief Number of required input artifacts
   *
   * The DAG executor validates that this many inputs are provided.
   * Return 0 for source stages (no inputs required).
   */
  virtual size_t required_input_count() const = 0;

  /**
   * @brief Number of output artifacts produced
   *
   * The DAG executor validates that execute() returns this many outputs.
   * Most stages return 1, but mergers and complex stages may return multiple
   * outputs.
   */
  virtual size_t output_count() const = 0;

  /**
   * @brief Generate diagnostic report about stage state
   *
   * Provides inspection of stage configuration and runtime state.
   * Useful for debugging and understanding pipeline behavior.
   *
   * @return Report with current state, or nullopt if not supported
   */
  virtual std::optional<StageReport> generate_report() const {
    return std::nullopt;  // Default: no reporting support
  }

  /**
   * @brief Declare observations required for this stage to operate
   *
   * Pipeline validation will ensure these observations are available
   * before execution begins. Most stages don't require observations.
   *
   * @return List of required observation keys
   */
  virtual std::vector<ObservationKey> get_required_observations() const {
    return {};  // Default: no required observations
  }

  /**
   * @brief Declare observations provided by this stage
   *
   * Stages may own observers and populate the context. This allows
   * pipeline validation to know what observations will be available.
   *
   * @return List of provided observation keys
   */
  virtual std::vector<ObservationKey> get_provided_observations() const {
    return {};  // Default: no provided observations
  }
};

/**
 * @brief Shared pointer to a stage
 *
 * Stages are shared across the DAG and should be managed via shared_ptr.
 */
using DAGStagePtr = std::shared_ptr<DAGStage>;

}  // namespace orc
