/*
 * File:        tbc_video_field_representation.h
 * Module:      orc-core
 * Purpose:     TBC video field representation
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2025-2026 Simon Inns
 */

#pragma once

#include <itbc_metadata_reader.h>

#include <fstream>
#include <memory>
#include <mutex>

#include "buffered_file_io.h"
#include "lru_cache.h"
#include "tbc_audio_efm_handler.h"
#include "tbc_reader.h"
#include "video_field_representation.h"

namespace orc {

// TODO: Observer system refactored - old observer friend declarations removed

/**
 * @brief Concrete implementation of VideoFieldRepresentation backed by a TBC
 * file (SOURCE stage)
 *
 * This class provides the bridge between raw TBC files and the abstract
 * VideoFieldRepresentation interface, implementing Phase 1 requirements.
 *
 * ARCHITECTURAL BOUNDARY - SOURCE STAGE RESPONSIBILITIES:
 * ========================================================
 *
 * INTERNAL (private to this stage):
 * - Reads TBC metadata from .tbc.json files via TBCMetadataReader
 * - Accesses TBC video samples from .tbc files via TBCReader
 * - Uses metadata internally for configuration and optimization
 *
 * EXTERNAL INTERFACE (for downstream stages):
 * - get_observations(): Returns observations generated by running observers
 *   on the actual video data (e.g., BiphaseObserver decodes VBI from samples)
 * - get_*_hint(): Returns hints derived from TBC metadata (e.g.,
 * field_phase_id)
 * - get_line(), get_descriptor(): Returns raw video data
 *
 * CRITICAL: Downstream stages must NEVER access TBC metadata directly.
 * All metadata information must flow through either:
 * 1. Observations (via get_observations()) - from analyzing video data
 * 2. Hints (via get_*_hint()) - from metadata
 *
 * This separation ensures:
 * - Clean architectural boundaries
 * - Testability with synthetic sources
 * - Reusability of stages with different source types
 */
class TBCVideoFieldRepresentation
    : public VideoFieldRepresentation,
      public TBCAudioEFMHandler::MetadataProvider {
 public:
  /**
   * @brief Create from an open TBC file and metadata
   *
   * @param tbc_reader Shared reader for TBC file data
   * @param metadata_reader Shared reader for metadata database
   * @param artifact_id Unique identifier for this artifact
   * @param provenance Provenance information
   */
  TBCVideoFieldRepresentation(
      std::shared_ptr<TBCReader> tbc_reader,
      std::shared_ptr<ITBCMetadataReader> metadata_reader,
      ArtifactID artifact_id, Provenance provenance);

  ~TBCVideoFieldRepresentation() override = default;

  // Prevent copying - represents large video data, share via shared_ptr instead
  TBCVideoFieldRepresentation(const TBCVideoFieldRepresentation&) = delete;
  TBCVideoFieldRepresentation& operator=(const TBCVideoFieldRepresentation&) =
      delete;

  // Prevent moving - instances should be managed via shared_ptr
  TBCVideoFieldRepresentation(TBCVideoFieldRepresentation&&) = delete;
  TBCVideoFieldRepresentation& operator=(TBCVideoFieldRepresentation&&) =
      delete;

  // VideoFieldRepresentation interface
  FieldIDRange field_range() const override;
  size_t field_count() const override;
  bool has_field(FieldID id) const override;

  std::optional<FieldDescriptor> get_descriptor(FieldID id) const override;

  const sample_type* get_line(FieldID id, size_t line) const override;
  std::vector<sample_type> get_field(FieldID id) const override;

  std::vector<DropoutRegion> get_dropout_hints(FieldID id) const override;
  std::optional<FieldParityHint> get_field_parity_hint(
      FieldID id) const override;
  std::optional<FieldPhaseHint> get_field_phase_hint(FieldID id) const override;
  std::optional<ActiveLineHint> get_active_line_hint() const override;

  std::optional<SourceParameters> get_video_parameters() const override {
    return video_params_;
  }

  // Audio interface
  uint32_t get_audio_sample_count(FieldID id) const override;
  std::vector<int16_t> get_audio_samples(FieldID id) const override;
  bool has_audio() const override;

  /**
   * @brief Set the PCM audio file path
   * @param pcm_path Path to .pcm audio file
   * @return true if file opened successfully, false otherwise
   */
  bool set_audio_file(const std::string& pcm_path);

  // EFM interface
  uint32_t get_efm_sample_count(FieldID id) const override;
  std::vector<uint8_t> get_efm_samples(FieldID id) const override;
  bool has_efm() const override;
  bool set_efm_file(const std::string& efm_path);

  // AC3 RF symbols interface
  uint32_t get_ac3_symbol_count(FieldID id) const override;
  std::vector<uint8_t> get_ac3_symbols(FieldID id) const override;
  bool has_ac3_rf() const override;
  bool set_ac3rf_symbols_file(const std::string& ac3rf_path);

  std::string type_name() const override {
    return "TBCVideoFieldRepresentation";
  }

  // VBI hint access from metadata (for GUI/diagnostics)
  std::optional<VbiData> get_vbi_hint(FieldID id) const override {
    if (!metadata_reader_) return std::nullopt;
    return metadata_reader_->read_vbi(id);
  }

 private:
  // TBC-specific accessors - private to enforce architectural boundaries
  // Only observers and the source stage itself should access TBC internals
  // Other stages must use the standard VideoFieldRepresentation interface
  const SourceParameters& video_parameters() const { return video_params_; }
  std::shared_ptr<ITBCMetadataReader> get_metadata_reader() const {
    return metadata_reader_;
  }
  std::optional<FieldMetadata> get_field_metadata(FieldID id) const override;

  // TODO: Observer system refactored - observers now access data via public
  // interface

  std::shared_ptr<TBCReader> tbc_reader_;
  std::shared_ptr<ITBCMetadataReader> metadata_reader_;

  SourceParameters video_params_;
  std::map<FieldID, FieldMetadata> field_metadata_cache_;

  // Audio and EFM handling delegated to shared handler
  std::unique_ptr<TBCAudioEFMHandler> audio_efm_handler_;

  // Access to metadata reader for internal use only
  const ITBCMetadataReader* metadata_reader() const {
    return metadata_reader_.get();
  }

  // Line data cache (for get_line calls)
  // Cache size: 500 fields × ~1.4MB/field = ~700MB max for preview navigation
  mutable LRUCache<FieldID, std::vector<sample_type>> field_data_cache_;
  static constexpr size_t MAX_CACHED_TBC_FIELDS = 500;

  void ensure_video_parameters();
  void ensure_field_metadata();

  // MetadataProvider interface implementation
  std::map<FieldID, FieldMetadata>& get_field_metadata_cache() override {
    return field_metadata_cache_;
  }
};

/**
 * @brief Factory function to create TBCVideoFieldRepresentation from files
 *
 * @param tbc_filename Path to .tbc file
 * @param metadata_filename Path to .tbc.json.db or .db file
 * @param pcm_filename Optional path to .pcm audio file
 * @param efm_filename Optional path to .efm EFM data file
 * @return Shared pointer to representation, or nullptr on failure
 */
std::shared_ptr<TBCVideoFieldRepresentation> create_tbc_representation(
    const std::string& tbc_filename, const std::string& metadata_filename,
    const std::string& pcm_filename = "", const std::string& efm_filename = "",
    const std::string& ac3rf_filename = "");

// Forward declaration for YC representation
class TBCYCVideoFieldRepresentation;

/**
 * @brief Factory function to create TBCYCVideoFieldRepresentation from separate
 * Y and C files
 *
 * @param y_filename Path to .tbcy (luma) file
 * @param c_filename Path to .tbcc (chroma) file
 * @param metadata_filename Path to .tbc.db metadata file
 * @param pcm_filename Optional path to .pcm audio file
 * @param efm_filename Optional path to .efm EFM data file
 * @return Shared pointer to representation, or nullptr on failure
 */
std::shared_ptr<TBCYCVideoFieldRepresentation> create_tbc_yc_representation(
    const std::string& y_filename, const std::string& c_filename,
    const std::string& metadata_filename, const std::string& pcm_filename,
    const std::string& efm_filename);

}  // namespace orc
